arch: amd64
language: java
jdk:
  - openjdk11
cache:
  false
branches:
  only:
    - master
    - staging
    - /^\d+\.\d+\.\d+$/
  except:
    - feature/*
    - bugfix/*
    - improvement/*
    - team/*
    - hackathon/*
    - revert-*
    - cherry-pick-*
    - VMTurbo_1
    - dependabot/*

install: skip

stages:
  - name: deploy
    if: type = push
  - name: pull-request-build
    if: type = pull_request

jobs:
  include:
    - stage: pull-request-build
      script:
        - echo "TODO add pull-request-build validation" && echo -e 'travis_fold:start:PullRequestBuild\\r'
        - echo -e 'travis_fold:end:PullRequestBuild\\r'
    - stage: deploy
      script:
        - echo "TODO add deploy validation" && echo -e 'travis_fold:start:Deploy\\r'
        - echo -e 'travis_fold:end:Deploy\\r'
