apiVersion: devops.turbonomic.io/v1alpha1
kind: AdviceMapping
metadata:
  labels:
    app.kubernetes.io/name: advicemapping
    app.kubernetes.io/instance: advicemapping-sample
    app.kubernetes.io/part-of: orm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: orm
  name: advicemapping-sample
spec:
  owner:
    name: myowner
    kind: Deployment
    apiVersion: apps/v1
  mappings:
  - ownerPath: .spec
    advisor:
      name: myadvisor
      path: .spec