apiVersion: devops.turbonomic.io/v1alpha1
kind: OperatorResourceMapping
metadata:
  labels:
    app.kubernetes.io/name: operatorresourcemapping
    app.kubernetes.io/instance: operatorresourcemapping-sample
    app.kubernetes.io/part-of: orm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: orm
  name: sample-operator
spec:
  operand:
    apiVersion: yourgroup.org/v1alpha1
    kind: yourkind
  patterns:
  - path: ".spec.template.spec.containers[?(@.name==container1)].resources"
    source:
      apiVersion: apps/v1
      kind: Deployment
      name: yourdeploy
      path: ".spec.template.spec.containers[?(@.name=container1)].resources"
status:
  mappings:
  - path: ".spec.template.spec.containers[?(@.name==container1)].resources"
    value:
      limits:
        cpu: 200m
        memory: 800Mi
      requests:
        cpu: 50m
        memory: 200Mi
    mapped: false
    message: "manually generated"
    reason: "for test"