# This is a sample ORM CR for WebSphere Liberty Operator v1.0.0 - Application CR
apiVersion: turbonomic.com/v1alpha1
kind: OperatorResourceMapping
metadata:
  name: openlibertyapplications.apps.openliberty.io
spec:
  resourceMappings:
    - srcResourceSpec:
        kind: Deployment
        componentNames:
        #supply the name of the deployments created
          - icetier1-app
      resourceMappingTemplates:
      #replace app with the name of your container
        - srcPath: .spec.template.spec.containers[?(@.name=="app")].resources
          destPath: .spec.resources