apiVersion: devops.turbonomic.io/v1alpha1
kind: OperatorResourceMapping
metadata:
  name: cp4mcm-hybridapp
spec:
  operand: # target same namespace by default
    apiVersion: deploy.hybridapp.io/v1alpha1
    kind: Operator
  enforcement: once # none, once, always
  mappings:
    components:
      containers:
      - "placement"
      - "deployable"
    patterns:
    - operandPath: .spec.core.{{containers}}.resources
      source:
        apiVersion: apps/v1
        kind: Deployment
        path: .spec.template.spec.containers[?(@.name=="{{containers}}")].resources
        matchLabels:
          app: cp4mcm-hybridapp
    - operandPath: .spec.replicas
      source:
        apiVersion: apps/v1
        kind: Deployment
        name: cp4mcm-hybridapp
        path: .spec.replicas
